import os
import json
import joblib
import tempfile
import shutil

import pandas as pd
import numpy as np
import xgboost as xgb

from sklearn.metrics import accuracy_score, log_loss
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_sample_weight

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEATURES_FILE = os.path.join(BASE_DIR, "data", "ml", "features_v4_unified.csv")
MODELS_DIR = os.path.join(BASE_DIR, "data", "models")
REPORTS_DIR = os.path.join(BASE_DIR, "data", "processed")

EXPECTED_ROWS = 484354
TRAIN_RATIO = 0.80
RANDOM_STATE = 42

# ★ Removed H2H features to match the dataset generated by Step 46
FEATURE_COLUMNS = [
    "home_elo_pre", "away_elo_pre", "elo_diff",
    "home_ewma_gf", "away_ewma_gf", "home_ewma_ga", "away_ewma_ga",
    "home_ewma_home_gf", "away_ewma_away_gf", "home_ewma_home_ga", "away_ewma_away_ga",
    "home_matches_before", "away_matches_before"
]

MARKETS = {
    "OU_0_5": {"target": "ou_0_5", "labels": ["OVER", "UNDER"]},
    "OU_1_5": {"target": "ou_1_5", "labels": ["OVER", "UNDER"]},
    "OU_2_5": {"target": "ou_2_5", "labels": ["OVER", "UNDER"]},
    "OU_3_5": {"target": "ou_3_5", "labels": ["OVER", "UNDER"]}
}

def atomic_write_json(data, file_path):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

def atomic_write_model(model, file_path):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    joblib.dump(model, file_path)

def train_market(df, market_key, config):
    target_col = config["target"]
    print(f"\n📈 TRAINING MARKET MODEL: {market_key}")
    
    X = df[FEATURE_COLUMNS].astype(float)
    y_raw = df[target_col].astype(str).str.upper()
    
    split_idx = int(len(df) * TRAIN_RATIO)
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train_raw, y_test_raw = y_raw.iloc[:split_idx], y_raw.iloc[split_idx:]
    
    le = LabelEncoder()
    y_train = le.fit_transform(y_train_raw)
    y_test = le.transform(y_test_raw)
    
    sample_weights = compute_sample_weight(class_weight="balanced", y=y_train)
    
    model = xgb.XGBClassifier(
        objective="binary:logistic", n_estimators=300, learning_rate=0.05,
        max_depth=6, subsample=0.85, colsample_bytree=0.85,
        random_state=RANDOM_STATE, n_jobs=-1, eval_metric="logloss", tree_method="hist"
    )
    model.fit(X_train, y_train, sample_weight=sample_weights)
    
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"   🎯 {market_key} Accuracy: {acc * 100:.2f}%")
    
    model_file = os.path.join(MODELS_DIR, f"market_{market_key.lower()}_model.joblib")
    atomic_write_model(model, model_file)
    
    label_mapping = {str(i): label for i, label in enumerate(le.classes_)}
    mapping_file = os.path.join(MODELS_DIR, f"market_{market_key.lower()}_label_mapping.json")
    atomic_write_json(label_mapping, mapping_file)

def train_correct_score_model(df):
    print("\n📈 TRAINING CORRECT SCORE MODEL (Multi-Class)")
    df["cs_home"] = df["home_goals"].clip(0, 5)
    df["cs_away"] = df["away_goals"].clip(0, 5)
    df["correct_score"] = df["cs_home"].astype(str) + "-" + df["cs_away"].astype(str)
    
    class_counts = df["correct_score"].value_counts()
    valid_classes = class_counts[class_counts > 500].index.tolist()
    df = df[df["correct_score"].isin(valid_classes)].copy()
    
    X = df[FEATURE_COLUMNS].astype(float)
    y_raw = df["correct_score"]
    
    split_idx = int(len(df) * TRAIN_RATIO)
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train_raw, y_test_raw = y_raw.iloc[:split_idx], y_raw.iloc[split_idx:]
    
    le = LabelEncoder()
    y_train = le.fit_transform(y_train_raw)
    y_test = le.transform(y_test_raw)
    
    sample_weights = compute_sample_weight(class_weight="balanced", y=y_train)
    
    model = xgb.XGBClassifier(
        objective="multi:softprob", num_class=len(le.classes_),
        n_estimators=400, learning_rate=0.05, max_depth=8,
        subsample=0.8, colsample_bytree=0.8, random_state=RANDOM_STATE,
        n_jobs=-1, eval_metric="mlogloss", tree_method="hist"
    )
    model.fit(X_train, y_train, sample_weight=sample_weights)
    
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"   🎯 Correct Score Top-1 Accuracy: {acc * 100:.2f}%")
    
    model_file = os.path.join(MODELS_DIR, "market_correct_score_model.joblib")
    atomic_write_model(model, model_file)
    
    label_mapping = {str(i): label for i, label in enumerate(le.classes_)}
    mapping_file = os.path.join(MODELS_DIR, "market_correct_score_label_mapping.json")
    atomic_write_json(label_mapping, mapping_file)
    print(f"   ✅ Saved: {model_file}")

def run():
    print("=" * 60)
    print(" ZOKASCORE V2 — STEP 49: EXTENDED MARKET & CS TRAINING")
    print("=" * 60)
    
    if not os.path.exists(FEATURES_FILE):
        raise FileNotFoundError(f"Dataset not found: {FEATURES_FILE}")
        
    df = pd.read_csv(FEATURES_FILE, low_memory=False)
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.sort_values(by=["date", "match_id"]).reset_index(drop=True)
    
    for market_key, config in MARKETS.items():
        train_market(df, market_key, config)
        
    train_correct_score_model(df)
    
    print("\n✅ STEP 49 COMPLETE: PASS")

if __name__ == "__main__":
    run()